//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemEngThermCal.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChemEngThermCal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Basing On 的本地化字符串。
        /// </summary>
        public static string abt_BaseOn {
            get {
                return ResourceManager.GetString("abt_BaseOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Us 的本地化字符串。
        /// </summary>
        public static string abt_ContactUs {
            get {
                return ResourceManager.GetString("abt_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cooperation 的本地化字符串。
        /// </summary>
        public static string abt_Cop {
            get {
                return ResourceManager.GetString("abt_Cop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you want to contribute to ChemEngThermCal, 的本地化字符串。
        /// </summary>
        public static string abt_Cop1 {
            get {
                return ResourceManager.GetString("abt_Cop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 or need our assistance in your own project, 的本地化字符串。
        /// </summary>
        public static string abt_Cop2 {
            get {
                return ResourceManager.GetString("abt_Cop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 welcome to contact us. 的本地化字符串。
        /// </summary>
        public static string abt_Cop3 {
            get {
                return ResourceManager.GetString("abt_Cop3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Contributors 的本地化字符串。
        /// </summary>
        public static string abt_MainContribut {
            get {
                return ResourceManager.GetString("abt_MainContribut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powered by Project ChemEngThermCal 的本地化字符串。
        /// </summary>
        public static string abt_PoweredBy {
            get {
                return ResourceManager.GetString("abt_PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statement 的本地化字符串。
        /// </summary>
        public static string abt_State {
            get {
                return ResourceManager.GetString("abt_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Program is for research and learning purpose only. 的本地化字符串。
        /// </summary>
        public static string abt_State1 {
            get {
                return ResourceManager.GetString("abt_State1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report of unfixed bugs and suggestions are always welcome. 的本地化字符串。
        /// </summary>
        public static string abt_State2 {
            get {
                return ResourceManager.GetString("abt_State2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zilin Song, W.I.T. 的本地化字符串。
        /// </summary>
        public static string abt_SZL {
            get {
                return ResourceManager.GetString("abt_SZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Powered By 的本地化字符串。
        /// </summary>
        public static string abt_UIBaseOn {
            get {
                return ResourceManager.GetString("abt_UIBaseOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UX Design 的本地化字符串。
        /// </summary>
        public static string abt_UX {
            get {
                return ResourceManager.GetString("abt_UX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aiguo Xuan, W.I.T. 的本地化字符串。
        /// </summary>
        public static string abt_XAG {
            get {
                return ResourceManager.GetString("abt_XAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Li Xiang, W.I.T. 的本地化字符串。
        /// </summary>
        public static string abt_XL {
            get {
                return ResourceManager.GetString("abt_XL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zhiguo Yan, W.I.T. 的本地化字符串。
        /// </summary>
        public static string abt_YZG {
            get {
                return ResourceManager.GetString("abt_YZG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression I 的本地化字符串。
        /// </summary>
        public static string atn_exp1 {
            get {
                return ResourceManager.GetString("atn_exp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression II 的本地化字符串。
        /// </summary>
        public static string atn_exp2 {
            get {
                return ResourceManager.GetString("atn_exp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression III 的本地化字符串。
        /// </summary>
        public static string atn_exp3 {
            get {
                return ResourceManager.GetString("atn_exp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cubic EOS Type 的本地化字符串。
        /// </summary>
        public static string ceos_Ceos {
            get {
                return ResourceManager.GetString("ceos_Ceos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string cfg_Lang {
            get {
                return ResourceManager.GetString("cfg_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Changes 的本地化字符串。
        /// </summary>
        public static string cfg_Save {
            get {
                return ResourceManager.GetString("cfg_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abort 的本地化字符串。
        /// </summary>
        public static string cm_abort {
            get {
                return ResourceManager.GetString("cm_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculate 的本地化字符串。
        /// </summary>
        public static string cm_calc {
            get {
                return ResourceManager.GetString("cm_calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculate Process 的本地化字符串。
        /// </summary>
        public static string cm_calproc {
            get {
                return ResourceManager.GetString("cm_calproc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditions 的本地化字符串。
        /// </summary>
        public static string cm_cdts {
            get {
                return ResourceManager.GetString("cm_cdts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Component - 1 的本地化字符串。
        /// </summary>
        public static string cm_chem1 {
            get {
                return ResourceManager.GetString("cm_chem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Component - 2 的本地化字符串。
        /// </summary>
        public static string cm_chem2 {
            get {
                return ResourceManager.GetString("cm_chem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chemical &amp; Properties 的本地化字符串。
        /// </summary>
        public static string cm_chemProp {
            get {
                return ResourceManager.GetString("cm_chemProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue 的本地化字符串。
        /// </summary>
        public static string cm_continue {
            get {
                return ResourceManager.GetString("cm_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Data 的本地化字符串。
        /// </summary>
        public static string cm_dbCon {
            get {
                return ResourceManager.GetString("cm_dbCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression of Equation 的本地化字符串。
        /// </summary>
        public static string cm_exp {
            get {
                return ResourceManager.GetString("cm_exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method 的本地化字符串。
        /// </summary>
        public static string cm_Method {
            get {
                return ResourceManager.GetString("cm_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Results 的本地化字符串。
        /// </summary>
        public static string cm_rst {
            get {
                return ResourceManager.GetString("cm_rst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string dbc_Cancel {
            get {
                return ResourceManager.GetString("dbc_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string dbc_Ok {
            get {
                return ResourceManager.GetString("dbc_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find database file &quot;cetcdb.mdb&quot; 的本地化字符串。
        /// </summary>
        public static string dbmng_db404 {
            get {
                return ResourceManager.GetString("dbmng_db404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using 2nd Virial coefficient 的本地化字符串。
        /// </summary>
        public static string gce_SecV {
            get {
                return ResourceManager.GetString("gce_SecV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using compressibility factor 的本地化字符串。
        /// </summary>
        public static string gce_Z {
            get {
                return ResourceManager.GetString("gce_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inquire the Compressibility Factor Diagram via the known 的本地化字符串。
        /// </summary>
        public static string gceCom_1 {
            get {
                return ResourceManager.GetString("gceCom_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And input 的本地化字符串。
        /// </summary>
        public static string gceCom_2 {
            get {
                return ResourceManager.GetString("gceCom_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method of Calculation 的本地化字符串。
        /// </summary>
        public static string gceP_Method {
            get {
                return ResourceManager.GetString("gceP_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activity Model 的本地化字符串。
        /// </summary>
        public static string mvle_actmodel {
            get {
                return ResourceManager.GetString("mvle_actmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antoine Constants 的本地化字符串。
        /// </summary>
        public static string mvle_Antoine {
            get {
                return ResourceManager.GetString("mvle_Antoine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fugacity Model 的本地化字符串。
        /// </summary>
        public static string mvle_fugmodel {
            get {
                return ResourceManager.GetString("mvle_fugmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Isobaric Bubble Point 的本地化字符串。
        /// </summary>
        public static string mvle_isobaricBubble {
            get {
                return ResourceManager.GetString("mvle_isobaricBubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Isobaric Dew Point 的本地化字符串。
        /// </summary>
        public static string mvle_isobaricDew {
            get {
                return ResourceManager.GetString("mvle_isobaricDew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Isothermal Bubble Point 的本地化字符串。
        /// </summary>
        public static string mvle_isothermBubble {
            get {
                return ResourceManager.GetString("mvle_isothermBubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Isothermal Dew Point 的本地化字符串。
        /// </summary>
        public static string mvle_isothermDew {
            get {
                return ResourceManager.GetString("mvle_isothermDew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Objective &amp; Model 的本地化字符串。
        /// </summary>
        public static string mvle_objtitle {
            get {
                return ResourceManager.GetString("mvle_objtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties of Fluid Mixture 的本地化字符串。
        /// </summary>
        public static string mvle_prop {
            get {
                return ResourceManager.GetString("mvle_prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ideal Model 的本地化字符串。
        /// </summary>
        public static string mvlest_ideal {
            get {
                return ResourceManager.GetString("mvlest_ideal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Realistic Model 的本地化字符串。
        /// </summary>
        public static string mvlest_real {
            get {
                return ResourceManager.GetString("mvlest_real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Semi-Ideal Model 的本地化字符串。
        /// </summary>
        public static string mvlest_semi {
            get {
                return ResourceManager.GetString("mvlest_semi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vapor - Liquid Equibrium Models 的本地化字符串。
        /// </summary>
        public static string mvlest_title {
            get {
                return ResourceManager.GetString("mvlest_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string mw_Abt {
            get {
                return ResourceManager.GetString("mw_Abt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info. About Us &amp; ChemEngThermCal. 的本地化字符串。
        /// </summary>
        public static string mw_AbtVc {
            get {
                return ResourceManager.GetString("mw_AbtVc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cubic E.O.S. 的本地化字符串。
        /// </summary>
        public static string mw_Ceos {
            get {
                return ResourceManager.GetString("mw_Ceos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Van der Waals, RK, SRK, PR. 的本地化字符串。
        /// </summary>
        public static string mw_CeosVc {
            get {
                return ResourceManager.GetString("mw_CeosVc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration 的本地化字符串。
        /// </summary>
        public static string mw_Cfg {
            get {
                return ResourceManager.GetString("mw_Cfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure ChemEngThermCal. 的本地化字符串。
        /// </summary>
        public static string mw_CfgVc {
            get {
                return ResourceManager.GetString("mw_CfgVc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control 的本地化字符串。
        /// </summary>
        public static string mw_Ctrl {
            get {
                return ResourceManager.GetString("mw_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chemical DataBase 的本地化字符串。
        /// </summary>
        public static string mw_Db {
            get {
                return ResourceManager.GetString("mw_Db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database State :  的本地化字符串。
        /// </summary>
        public static string mw_DbStt {
            get {
                return ResourceManager.GetString("mw_DbStt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 See about the chemical property database. 的本地化字符串。
        /// </summary>
        public static string mw_DbVc {
            get {
                return ResourceManager.GetString("mw_DbVc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Error : Please specify the model to calculate. Select one of the Radio Buttons. 的本地化字符串。
        /// </summary>
        public static string mw_Err_1 {
            get {
                return ResourceManager.GetString("mw_Err_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Error : Please specify the model to calculate. Blank selection of the Combo Box. 的本地化字符串。
        /// </summary>
        public static string mw_Err_2 {
            get {
                return ResourceManager.GetString("mw_Err_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Error : Please specify the model to calculate. Check input in the Textbox. 的本地化字符串。
        /// </summary>
        public static string mw_Err_3 {
            get {
                return ResourceManager.GetString("mw_Err_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generalized Correlation 的本地化字符串。
        /// </summary>
        public static string mw_Gc {
            get {
                return ResourceManager.GetString("mw_Gc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Second virial coefficient etc. 的本地化字符串。
        /// </summary>
        public static string mw_GcVc {
            get {
                return ResourceManager.GetString("mw_GcVc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing... 的本地化字符串。
        /// </summary>
        public static string mw_Inil {
            get {
                return ResourceManager.GetString("mw_Inil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multicomponent Mixtures 的本地化字符串。
        /// </summary>
        public static string mw_Mf {
            get {
                return ResourceManager.GetString("mw_Mf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Functions 的本地化字符串。
        /// </summary>
        public static string mw_Of {
            get {
                return ResourceManager.GetString("mw_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More attached calculations 的本地化字符串。
        /// </summary>
        public static string mw_OfVc {
            get {
                return ResourceManager.GetString("mw_OfVc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One Component System 的本地化字符串。
        /// </summary>
        public static string mw_Pf {
            get {
                return ResourceManager.GetString("mw_Pf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gas Mixing Rule 的本地化字符串。
        /// </summary>
        public static string mw_Rgm {
            get {
                return ResourceManager.GetString("mw_Rgm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E.O.S. and Kay&apos;s rule. 的本地化字符串。
        /// </summary>
        public static string mw_RgmVc {
            get {
                return ResourceManager.GetString("mw_RgmVc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vapor - Liquid Equilibrium 的本地化字符串。
        /// </summary>
        public static string mw_Vle {
            get {
                return ResourceManager.GetString("mw_Vle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For mixed fluid using E.O.S and activity. 的本地化字符串。
        /// </summary>
        public static string mw_VleMfVc {
            get {
                return ResourceManager.GetString("mw_VleMfVc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For pure fluid using E.O.S method. 的本地化字符串。
        /// </summary>
        public static string mw_VlePfVc {
            get {
                return ResourceManager.GetString("mw_VlePfVc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antoine Equation 的本地化字符串。
        /// </summary>
        public static string ofst_antoine {
            get {
                return ResourceManager.GetString("ofst_antoine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generalized correlations 的本地化字符串。
        /// </summary>
        public static string ofst_gceCalP {
            get {
                return ResourceManager.GetString("ofst_gceCalP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pressure calculation using generalized correlations 的本地化字符串。
        /// </summary>
        public static string ofst_gceCalPDetail {
            get {
                return ResourceManager.GetString("ofst_gceCalPDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rackett Equation 的本地化字符串。
        /// </summary>
        public static string ofst_rackett {
            get {
                return ResourceManager.GetString("ofst_rackett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Functions 的本地化字符串。
        /// </summary>
        public static string ofst_title {
            get {
                return ResourceManager.GetString("ofst_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Isobaric 的本地化字符串。
        /// </summary>
        public static string pvle_isobaric {
            get {
                return ResourceManager.GetString("pvle_isobaric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Isothemal 的本地化字符串。
        /// </summary>
        public static string pvle_isothermal {
            get {
                return ResourceManager.GetString("pvle_isothermal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binary Interaction Index K = 的本地化字符串。
        /// </summary>
        public static string rgm_binK {
            get {
                return ResourceManager.GetString("rgm_binK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cubic E.O.S. mix rule 的本地化字符串。
        /// </summary>
        public static string rgm_Ceos {
            get {
                return ResourceManager.GetString("rgm_Ceos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kay&apos;s rule 的本地化字符串。
        /// </summary>
        public static string rgm_Kay {
            get {
                return ResourceManager.GetString("rgm_Kay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mix Model 的本地化字符串。
        /// </summary>
        public static string rgm_MixModel {
            get {
                return ResourceManager.GetString("rgm_MixModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties of Gas Mixture 的本地化字符串。
        /// </summary>
        public static string rgm_Prop {
            get {
                return ResourceManager.GetString("rgm_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Second virial coefficient mix rule 的本地化字符串。
        /// </summary>
        public static string rgm_SecV {
            get {
                return ResourceManager.GetString("rgm_SecV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try Tabs On The Left. 的本地化字符串。
        /// </summary>
        public static string stt_trytab {
            get {
                return ResourceManager.GetString("stt_trytab", resourceCulture);
            }
        }
    }
}
